### PR TITLE
Keyboard friendly

### PR DESCRIPTION
**Pull request by Nerten**

### CODE REVIEW

**Comment by soywiz** [comment]
Cool. Thanks!

**Comment by gordon0001** [comment]
now we have a .DS_Store file in our repo that doesnt belong to the project because you didnt check.

**Comment by soywiz** [comment]
Regarding to the DS_Store. I missed it when reviewed it on my phone. Hope it was not too big. If was is, we can recreate git history filtering that file.

**Comment by Nerten** [comment]
I'm so sorry about DS_Store files.

**Pull request merged**
