### PR TITLE
Vitaminversion

### PR DESCRIPTION
**Pull request by luckylucks**
By examing the size of steroid.surpx or mai.surpx the version can be determined. The Information is is displayed in JMenuItem.
The compression level seems to be off in java. Maximum compression level in java seems to 8.

### CODE REVIEW

**Comment by soywiz** [comment]
Cool! Thanks! :)

Fixes #23

**Comment by soywiz** [comment]
@luckylucks 

I have reviewed this already. A couple of comments:

The integer that returns `ZipEntry.getMethod()` is an enum:

```
/**
 * Compression method for uncompressed entries.
 */
public static final int STORED = 0;

/**
 * Compression method for compressed (deflated) entries.
 */
public static final int DEFLATED = 8;
```

So 8 doesn't mean that it has the compression level 8, but that it used the deflate algorithm (that is the default). I don't think that the compression level is stored anywhere in a deflate stream. So the only way I can think to get this information is to uncompress a small file from the vpk, and recompress with several levels and try to find the one that has the nearest size. Depending on the size of the file, this process could be a bit costly.

---

A functional way of doing this (with kotlin):
```
fun findDumperBySize(size: Long) : DumperNames {
        for (dumper in DumperNames.values()) {
            if (size == dumper.size)
                return dumper
        }
        return DumperNames.UNKNOWN
    }
```

is equivalent to this:
```
fun findDumperBySize(size: Long) = DumperNames.values().firstOrNull { it.size == size } ?: DumperNames.UNKNOWN
```

That grabs the values from DumperNames and finds the first element that fullfils the condition (that the `element.size == size`) or *null* if cannot be found. The `?:` produces the right value when the left is null. Also kotlin inlines that so it won't generate any object for the condition and the performance should be the same.

Also noticed in other commits for the renaming functionality that you were using:
`for (v in 0..N - 1)` that can be converted to `for (v in 0 until N)` or `for (v in collection.indices)` or `for ((index, item) in collection.withIndex())`

I'm totally ok with your code and I'm not touching it at all. But wanted to notice just in the case you didn't know that about Kotlin. And thank you for your work! :)

**Comment by luckylucks** [comment]
> So 8 doesn't mean that it has the compression level 8, but that it used the deflate algorithm (that is the default). I don't think that the compression level is stored anywhere in a deflate stream.

You are right. The method returns only the used compression algorithm stored in the zip header. After looking into the zip-specification I have not found specific field to store the used compression level. The field for generic additional information is not used in the vpk-files I checked and the deflate algorithm also does not store such information.

> I'm totally ok with your code and I'm not touching it at all. But wanted to notice just in the case you didn't know that about Kotlin. And thank you for your work! :)

You can change it, or maybe I do it later.
I'm more used to Java 6/7 (never used kotlin before), I haven't adapted to lambdas yet, but it seems easier than Java stream api for collections.

**Comment by soywiz** [comment]
I though that you never used kotlin, that's why I told you some of the cool things about it.
I didn't want to sound picky or something, but since you did the effort to writting it, I wanted to share those tips. But not going to change your code, that works just fine. In the case you want, you can change it yourself in other PR.

Java streams are a bit messy. Doesn't inline + works with defaults method. That I think it is not a very good design. Kotlin inlines + allows to add extension methods everywhere which is better.

The cool thing about extension methods + lambdas is that you can read from left to right. So you start with a subject, in this case a collection, and starts transformating that result until it reaches the expected result. So it is readable, and keeps immutability which prevents lots of bugs.

Also you can add .java files directly in the src folder and it should work, kotlin supports bidirecional interoperability if you feel more comfortable with java, I'm ok with that too :)

**Pull request merged**
